### ISSUE TITLE
无法上传到SVN目录

### ISSUE THREAD

**Issue by Tree503** [NingOpenSource/vcsLib#1]
我在本地搭建了SVN环境，复制了目录的url赋给repoUri，但是上传的jar包都在vcsLibHome目录下的$repoUri目录下。
这个vcsLibHome是什么意思？

**Comment by Lyon1994** [comment]
vcsLibHome是本地的maven仓库目录（可以不配置，默认存储到$USER_HOME/.vcsLib目录下），上传的原理是先将jar包上传至本地maven仓库，再将本地maven仓库与svn服务器或者git服务器同步，这里主要是同步操作，所以需要你在svn服务器上先创建一个目录，然后在vcsLib.properties文件中配置，

**Comment by Lyon1994** [comment]
![image](https://user-images.githubusercontent.com/8456652/61035782-5e414c80-a3fa-11e9-8547-ff65b46eac9d.png)
比如这样

**Comment by Lyon1994** [comment]
如果仍然不行，就涉及到svn环境的问题，这个比较复杂，建议打开到vcsLibHome所指向的目录手动同步文件
